sonar.sources=src
sonar.tests=src,test

sonar.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.test.ts

sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.test.ts

sonar.cpd.exclusions=**/*.spec.ts,**/*.e2e-spec.ts,**/*.test.ts